--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [Movie] ON

MERGE INTO [Movie] AS [Target]
USING (VALUES
  (1,N'The Shawshank Redemption',N'Drama',N'9.3','1994-05-05T00:00:00',N'images/src',N'alice')
 ,(2,N'The Godfather',N'Crime',N'9.2','1972-05-05T00:00:00',N'images/src',N'alice')
 ,(3,N'The Dark Knight',N'Action',N'9.1','2008-05-05T00:00:00',N'images/src',N'bob')
 ,(4,N'12 Angry Men',N'Crime',N'8.9','1957-05-05T00:00:00',N'images/src',N'bob')
 ,(5,N'Schindler''s List',N'Biography',N'8.9','1993-05-05T00:00:00',N'images/src',N'alice')
 ,(6,N'Pulp Fiction',N'Drama',N'8.9','1994-05-05T00:00:00',N'images/src',N'alice')
 ,(7,N'Fight Club',N'Drama',N'8.8','1999-05-05T00:00:00',N'images/src',N'bob')
 ,(8,N'Forrest Gump',N'Romance',N'8.8','1994-05-05T00:00:00',N'images/src',N'bob')
) AS [Source] ([Id],[Title],[Genre],[Rating],[ReleaseDate],[ImageUrl],[Owner])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
	NULLIF([Source].[Title], [Target].[Title]) IS NOT NULL OR NULLIF([Target].[Title], [Source].[Title]) IS NOT NULL OR 
	NULLIF([Source].[Genre], [Target].[Genre]) IS NOT NULL OR NULLIF([Target].[Genre], [Source].[Genre]) IS NOT NULL OR 
	NULLIF([Source].[Rating], [Target].[Rating]) IS NOT NULL OR NULLIF([Target].[Rating], [Source].[Rating]) IS NOT NULL OR 
	NULLIF([Source].[ReleaseDate], [Target].[ReleaseDate]) IS NOT NULL OR NULLIF([Target].[ReleaseDate], [Source].[ReleaseDate]) IS NOT NULL OR 
	NULLIF([Source].[ImageUrl], [Target].[ImageUrl]) IS NOT NULL OR NULLIF([Target].[ImageUrl], [Source].[ImageUrl]) IS NOT NULL OR 
	NULLIF([Source].[Owner], [Target].[Owner]) IS NOT NULL OR NULLIF([Target].[Owner], [Source].[Owner]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[Title] = [Source].[Title], 
  [Target].[Genre] = [Source].[Genre], 
  [Target].[Rating] = [Source].[Rating], 
  [Target].[ReleaseDate] = [Source].[ReleaseDate], 
  [Target].[ImageUrl] = [Source].[ImageUrl], 
  [Target].[Owner] = [Source].[Owner]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[Title],[Genre],[Rating],[ReleaseDate],[ImageUrl],[Owner])
 VALUES([Source].[Id],[Source].[Title],[Source].[Genre],[Source].[Rating],[Source].[ReleaseDate],[Source].[ImageUrl],[Source].[Owner])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;

DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [Movie]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[Movie] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO



SET IDENTITY_INSERT [Movie] OFF
SET NOCOUNT OFF
GO