--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [ApiScope] ON

MERGE INTO [ApiScope] AS [Target]
USING (VALUES
  (1,1,N'movieApi',N'Movie Api',NULL,0,0,1)
) AS [Source] ([Id],[Enabled],[Name],[DisplayName],[Description],[Required],[Emphasize],[ShowInDiscoveryDocument])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
	NULLIF([Source].[Enabled], [Target].[Enabled]) IS NOT NULL OR NULLIF([Target].[Enabled], [Source].[Enabled]) IS NOT NULL OR 
	NULLIF([Source].[Name], [Target].[Name]) IS NOT NULL OR NULLIF([Target].[Name], [Source].[Name]) IS NOT NULL OR 
	NULLIF([Source].[DisplayName], [Target].[DisplayName]) IS NOT NULL OR NULLIF([Target].[DisplayName], [Source].[DisplayName]) IS NOT NULL OR 
	NULLIF([Source].[Description], [Target].[Description]) IS NOT NULL OR NULLIF([Target].[Description], [Source].[Description]) IS NOT NULL OR 
	NULLIF([Source].[Required], [Target].[Required]) IS NOT NULL OR NULLIF([Target].[Required], [Source].[Required]) IS NOT NULL OR 
	NULLIF([Source].[Emphasize], [Target].[Emphasize]) IS NOT NULL OR NULLIF([Target].[Emphasize], [Source].[Emphasize]) IS NOT NULL OR 
	NULLIF([Source].[ShowInDiscoveryDocument], [Target].[ShowInDiscoveryDocument]) IS NOT NULL OR NULLIF([Target].[ShowInDiscoveryDocument], [Source].[ShowInDiscoveryDocument]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[Enabled] = [Source].[Enabled], 
  [Target].[Name] = [Source].[Name], 
  [Target].[DisplayName] = [Source].[DisplayName], 
  [Target].[Description] = [Source].[Description], 
  [Target].[Required] = [Source].[Required], 
  [Target].[Emphasize] = [Source].[Emphasize], 
  [Target].[ShowInDiscoveryDocument] = [Source].[ShowInDiscoveryDocument]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[Enabled],[Name],[DisplayName],[Description],[Required],[Emphasize],[ShowInDiscoveryDocument])
 VALUES([Source].[Id],[Source].[Enabled],[Source].[Name],[Source].[DisplayName],[Source].[Description],[Source].[Required],[Source].[Emphasize],[Source].[ShowInDiscoveryDocument])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;

DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [ApiScope]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[ApiScope] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO



SET IDENTITY_INSERT [ApiScope] OFF
SET NOCOUNT OFF
GO