--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [ClientGrantType] ON

MERGE INTO [ClientGrantType] AS [Target]
USING (VALUES
  (1,N'hybrid',1)
) AS [Source] ([Id],[GrantType],[ClientId])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
	NULLIF([Source].[GrantType], [Target].[GrantType]) IS NOT NULL OR NULLIF([Target].[GrantType], [Source].[GrantType]) IS NOT NULL OR 
	NULLIF([Source].[ClientId], [Target].[ClientId]) IS NOT NULL OR NULLIF([Target].[ClientId], [Source].[ClientId]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[GrantType] = [Source].[GrantType], 
  [Target].[ClientId] = [Source].[ClientId]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[GrantType],[ClientId])
 VALUES([Source].[Id],[Source].[GrantType],[Source].[ClientId])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;


SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [ClientGrantType]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[ClientGrantType] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END



SET IDENTITY_INSERT [ClientGrantType] OFF
SET NOCOUNT OFF
