--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [ClientPostLogoutRedirectUri] ON

MERGE INTO [ClientPostLogoutRedirectUri] AS [Target]
USING (VALUES
  (1,N'https://localhost:44060/signout-callback-oidc',1)
) AS [Source] ([Id],[PostLogoutRedirectUri],[ClientId])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
	NULLIF([Source].[PostLogoutRedirectUri], [Target].[PostLogoutRedirectUri]) IS NOT NULL OR NULLIF([Target].[PostLogoutRedirectUri], [Source].[PostLogoutRedirectUri]) IS NOT NULL OR 
	NULLIF([Source].[ClientId], [Target].[ClientId]) IS NOT NULL OR NULLIF([Target].[ClientId], [Source].[ClientId]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[PostLogoutRedirectUri] = [Source].[PostLogoutRedirectUri], 
  [Target].[ClientId] = [Source].[ClientId]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[PostLogoutRedirectUri],[ClientId])
 VALUES([Source].[Id],[Source].[PostLogoutRedirectUri],[Source].[ClientId])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;


SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [ClientPostLogoutRedirectUri]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[ClientPostLogoutRedirectUri] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END




SET IDENTITY_INSERT [ClientPostLogoutRedirectUri] OFF
SET NOCOUNT OFF
