--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [ClientRedirectUri] ON

MERGE INTO [ClientRedirectUri] AS [Target]
USING (VALUES
  (1,N'https://localhost:44360/signin-oidc',1)
) AS [Source] ([Id],[RedirectUri],[ClientId])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
	NULLIF([Source].[RedirectUri], [Target].[RedirectUri]) IS NOT NULL OR NULLIF([Target].[RedirectUri], [Source].[RedirectUri]) IS NOT NULL OR 
	NULLIF([Source].[ClientId], [Target].[ClientId]) IS NOT NULL OR NULLIF([Target].[ClientId], [Source].[ClientId]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[RedirectUri] = [Source].[RedirectUri], 
  [Target].[ClientId] = [Source].[ClientId]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[RedirectUri],[ClientId])
 VALUES([Source].[Id],[Source].[RedirectUri],[Source].[ClientId])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;

DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [ClientRedirectUri]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[ClientRedirectUri] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO



SET IDENTITY_INSERT [ClientRedirectUri] OFF
SET NOCOUNT OFF
GO