--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [IdentityResourceClaim] ON

MERGE INTO [IdentityResourceClaim] AS [Target]
USING (VALUES
  (1,1,N'picture')
 ,(2,4,N'email')
 ,(3,3,N'address')
 ,(4,2,N'sub')
 ,(5,1,N'updated_at')
 ,(6,1,N'locale')
 ,(7,1,N'zoneinfo')
 ,(8,1,N'birthdate')
 ,(9,4,N'email_verified')
 ,(10,1,N'gender')
 ,(11,1,N'name')
 ,(12,1,N'family_name')
 ,(13,1,N'given_name')
 ,(14,1,N'middle_name')
 ,(15,1,N'nickname')
 ,(16,1,N'preferred_username')
 ,(17,1,N'profile')
 ,(18,1,N'website')
 ,(19,5,N'role')
) AS [Source] ([Id],[IdentityResourceId],[Type])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
	NULLIF([Source].[IdentityResourceId], [Target].[IdentityResourceId]) IS NOT NULL OR NULLIF([Target].[IdentityResourceId], [Source].[IdentityResourceId]) IS NOT NULL OR 
	NULLIF([Source].[Type], [Target].[Type]) IS NOT NULL OR NULLIF([Target].[Type], [Source].[Type]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[IdentityResourceId] = [Source].[IdentityResourceId], 
  [Target].[Type] = [Source].[Type]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[IdentityResourceId],[Type])
 VALUES([Source].[Id],[Source].[IdentityResourceId],[Source].[Type])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;


SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [IdentityResourceClaim]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[IdentityResourceClaim] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END




SET IDENTITY_INSERT [IdentityResourceClaim] OFF
SET NOCOUNT OFF
